# Generated by Django 6.0.2 on 2026-02-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_no', models.CharField()),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_age', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
